name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.x

    - name: Set up Node JS
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.0

    - name: Checkout perftop package
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./gradlew clean
        ./gradlew build -Dbuild.snapshot=false -Dbuild.linux=true
        ./gradlew build -Dbuild.snapshot=false -Dbuild.macos=true
        mkdir artifacts
        macos_artifact=`ls build/distributions/*macos*.zip`
        linux_artifact=`ls build/distributions/*linux*.zip`
        cp $macos_artifact artifacts/
        cp $linux_artifact artifacts/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Upload Artifacts to S3
      run: |
        macos=`ls artifacts/*macos*.zip`
        linux=`ls artifacts/*linux*.zip`

        # Inject the build number before the suffix
        macos_outfile=`basename ${macos%.zip}-build-${GITHUB_RUN_NUMBER}.zip`
        linux_outfile=`basename ${linux%.zip}-build-${GITHUB_RUN_NUMBER}.zip`

        s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/elasticsearch-clients/perftop/"

        echo "Copying ${macos} to ${s3_prefix}${macos_outfile}"
        aws s3 cp --quiet $macos ${s3_prefix}${macos_outfile}

        echo "Copying ${linux} to ${s3_prefix}${linux_outfile}"
        aws s3 cp --quiet $linux ${s3_prefix}${linux_outfile}

    - name: Upload Workflow Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts/
