name: CD

on:
  push:
    branches:
      - 'rguo*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.x

    - name: Set up Node JS
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.0

    - name: Checkout perftop package
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./gradlew clean
        ./gradlew build -Dbuild.snapshot=false -Dbuild.linux=true
        ./gradlew build -Dbuild.snapshot=false -Dbuild.macos=true
        mkdir artifacts
        macos_artifact=`ls build/distributions/*MACOS*.zip`
        linux_artifact=`ls build/distributions/*LINUX*.zip`
        cp $macos_artifact artifacts/
        cp $linux_artifact artifacts/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Upload Artifacts to S3
      run: |
        s3_path=s3://artifacts.opendistroforelasticsearch.amazon.com/downloads
        aws s3 cp artifacts/*MACOS*.zip $s3_path/perftop/
        aws s3 cp artifacts/*LINUX*.zip $s3_path/perftop/
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"

    - name: Upload Workflow Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts/